### ISSUE TITLE
Harmonogram

### ISSUE THREAD

**Issue by kasianw** [MistrzowieKodowania/cPlusPlusMaterials#14]
Dla wszystkich, którzy tak jak ja potrzebują mieć wszystko w jednym miejscu:

*_2.02 19.00 Podstawy języka C++ 
9.02 19.00 Podstawy języka C++, cz.1 
16.02 19.00 Tablice i funkcje 
23.02 19.00 Klasy i obiekty 
8.03 19.00 Klasy i obiekty 
22.03 19.00 Obługa plików 
5.04 19.00 Metody wirtualne 
19.04 19.00 Poliformizm i szablony 
10.05 19.00 Poliformizm i szablony 
24.05 19.00 Co dalej ? *_

**Comment by ksorokosz** [comment]
@kasianw 

wrzuciłem do naszego README. Dzięki i przepraszam, że wcześniej tego nie wrzuciłem :)

**Comment by Tigersoftis** [comment]
dzięki :)
