### ISSUE TITLE
Otwieramy forum :)

### ISSUE THREAD

**Issue by ksorokosz** [MistrzowieKodowania/cPlusPlusMaterials#2]
Cześć wszystkim!

Github to nie tylko repozytorium kodu, ale również społeczność.
Na głównej stronie projektu znajdziecie linki do tutoriali, do serwisów, które polecam, albo które pojawiły się na chacie podczas Webinarium.
Znajdziecie tutaj również kod wraz z komentarzami, które często będą odpowiedziami na Wasze pytania. Dzisiaj wrzuciłem kod który wyświetla na ekranie polskie znaki :) Za kilka godzin pojawi się tutaj również kod do kolejnych zajęć! Możecie go ściągnąć, śledzić razem ze mną, modyfikować i uruchamiać w trakcie Webinarium - do czego Was zachęcam!

Tutaj w końcu znajdziecie wskazówki do projektów i materiały, które będą Wam potrzebne aby zostać agentem wywiadu, grafikiem, inżynierem dźwięku albo specjalistą od baz danych.

Pozdrawiam i biorę się za przygotowanie kolejnych zajęć :)
Do zobaczenia we wtorek.

**Comment by EMCsoftware** [comment]
Bardzo fajnie, akurat zacząłem pisać prototyp projektu o bibliotece i testowałem różne sposoby wyświetlania polskich znaków z internetu, lecz żaden nie działał, spróbuję użyć tego. Mam jeszcze jedno pytanie, czy kod musi być przenośny, czy mogę używać dobrodziejstw biblioteki Windows?

**Comment by ksorokosz** [comment]
Jeśli pytasz mnie o projekt to kod nie musi być przenośny - nie nakładam tutaj żadnych limitów. Czasami jednak dużo więcej nauczymy się tworząc kod przenośny. Zawsze możemy podejść do problemu w taki sposób, że na początek skorzystamy z mniej przenośnego rozwiązania po to aby później zastąpić je czymś bardziej uniwersalnym lub lepszym. Taki proces nazywa się refaktoryzacją i jest czymś zupełnie normalnym: https://pl.wikipedia.org/wiki/Refaktoryzacja

Jeśli chodzi o wyświetlanie polskich znaków: kod, który wrzuciłem dopasowany jest poziomem do tego o czym mówiliśmy do tej pory. W przypadku projektu biblioteki na samym początku może być wystarczający, ale później pokażę Wam coś bardziej uniwersalnego, a może ktoś mnie wyprzedzi ;)

Zachęcam więc do tego żeby te projekty rozwijały się razem z Waszą wiedzą o C++. Jeśli coś uda się Wam zrobić, a usłyszecie, znajdziecie lepsze rozwiązanie śmiało korzystajcie. Sami też wrzucajcie rozwiązania i pomysły. Ściąganie jest nawet wskazane! Ja też mogę się dzięki temu dużo nauczyć :)

**Comment by kasianw** [comment]
W jaki sposób mogę usunąć repozytorium na swoim koncie?

**Comment by ksorokosz** [comment]
Kasia :) widziałem, że zadałaś pytanie jak wyrzucić repozytorium z GitHuba. Jednocześnie zamknęłaś tę dyskusję, więc to pytanie nie wyświetliło się ;) 
Usunąć repozytorium możemy przechodząc na stronę wybranego repozytorium. Nad kodem powinien znajdować się pasek z zakładkami:
Code, Issues, Pull requests, Wiki, Pulse itd.
Znajduje się tam również zakładka Settings. Jeśli ją wybierzemy i zjedziemy na sam dół strony zobaczymy sekcję: "Danger Zone" (zaznaczona na czerwono). Tam znajduje się przycisk pozwalający m.in usunąć repozytorium. Potem wystarczy usunąć kod z naszego dysku na komputerze.

**Comment by kasianw** [comment]
Dziękuję, własnie pokasowałam to co nie jest mi potrzebne. :)
Muszę się trochę oswoić z nowym środowiskiem. ;)
