### ISSUE TITLE
Zadanie

### ISSUE THREAD

**Issue by radekord** [MistrzowieKodowania/cPlusPlusMaterials#4]
Na czym polega to zadanie? Jeżeli dobrze pamiętam, to mieliśmy zrobic 'Hello world' tak? Jak ma to dokładnie wyglądać?

**Comment by ksorokosz** [comment]
Chcielibyśmy żebyście zrobili program Hello World (taki napis ma się pojawić na ekranie). Potem wrzucili ten kod na własne konto na GitHubie. Pomogą Wam w tym tutoriale do których linki są dostępne na tej stronie: https://github.com/MistrzowieKodowania/cPlusPlusMaterials
Spróbujcie też ściągnąć repozytorium cPlusPlusMaterials na Wasze komputery, uruchomić programy, które widzieliście na poprzednich zajęciach. Ściągając to repozytorium będziecie mogli śledzić i uruchamiać kod, który pokazuję w trakcie Webinarium - również na tym najbliższym już we wtorek.

Zachęcam Was również do dzielenia się kodem, który napiszecie (np. projektami) w repozytorium cPlusPlusMasters. W ten sposób Wasi znajomi z Webinarium oraz ja będziemy mogli go zobaczyć, udzielić wskazówek albo skorzystać z Waszych rozwiązań. 

W przypadku problemów i pytań piszcie tutaj. Zobaczą je uczestnicy Webinarium oraz ja. Zachęcam do dyskusji i wzajemnej pomocy. Sam również postaram się odpowiadać na pytania, tutaj albo na zajęciach.

**Comment by radekord** [comment]
Chodzi o takie coś?
​

**Comment by ksorokosz** [comment]
na Twoim koncie pojawiło się repozytorium, ale nie ma tam jeszcze kodu. Chodzi o to aby ten kod tam się pojawił.
Spójrz na moim profilu: https://github.com/ksorokosz/HelloWorld

**Comment by radekord** [comment]
Eh, a jak udostępnić KOD w danym repozytorium? nie moge znalezc wyjscia
.____.

**Comment by ksorokosz** [comment]
czy obejrzałeś tutorial, który udostępniliśmy?
Linki do tutoriala są tutaj: https://github.com/MistrzowieKodowania/cPlusPlusMaterials
Ostatni tutorial tzn. "Git. Jak korzystać?" pokazuje krok po kroku jak wrzucić kod do repozytorium.

Uzupełnię to jeszcze w taki sposób, że ten kod oczywiście trzeba napisać i wskazać potem w kliencie, o którym mowa w tutorialu :)

**Comment by radekord** [comment]
ah dobrze, to nie wazne D:

W dniu 7 lutego 2016 10:06 użytkownik Kamil Sorokosz <
notifications@github.com> napisał:

**Comment by sp15informatyka** [comment]
Oczywiście moje VS robi trochę bałaganu w katalogach ale czy to jest zadowalające?
[https://github.com/sp15informatyka/MK_Cplusplus/tree/master/HelloWorld/HelloWorld](url)

**Comment by ksorokosz** [comment]
Jest w porządku :)

**Comment by Tigersoftis** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 

Hej 
jak uruchomiæ desktopowy github? oprócz loginu i passwordu wo³a o jaki¶ serwer i nie wiem co tam wpisaæ :(

**Comment by Tigersoftis** [comment]
blockquote {padding-left: 1ex; margin: 0px 0px 0px 0.8ex; border-left: #cccccc 1px solid;} p {margin: 0px;padding: 0px;} 
Dnia Niedziela, 7 Lutego 2016 10:06 Kamil Sorokosz <notifications@github.com> napisał(a)

czy obejrzałeś tutorial, który udostępniliśmy? Linki do tutoriala są tutaj: https://github.com/MistrzowieKodowania/cPlusPlusMaterials Ostatni tutorial tzn. "Git. Jak korzystać?" pokazuje krok po kroku jak wrzucić kod do repozytorium.
Uzupełnię to jeszcze w taki sposób, że ten kod oczywiście trzeba napisać i wskazać potem w kliencie, o którym mowa w tutorialu :)
 
 
tylko ze klient nie działa :(

**Comment by Tigersoftis** [comment]
Wersja desktopowa githuba nie działa, nie wiem co wpisać w polu gdzie chcą jakiś serwer oprócz loginu i passworda :(

a przez webową stronę nic nie wiem jak zrobić bo jest mało intuicyjna :(

**Comment by Tigersoftis** [comment]
wrzuciłem dwa programy webowo ale nie wiem czy tak to ma byc ?

**Comment by ksorokosz** [comment]
Tigersoftis, utworzyłeś repozytoria i napisałeś kilka działających programów. Kod wkleiłeś do Issues, ale to jest miejsce do dyskutowania (tak jak robimy to tutaj).
Jeśli chodzi natomiast o wrzucenie kodu na Githuba, spójrz na przykład na moim profilu albo na profilach Twoich kolegów i koleżanek, którzy sobie poradzili - tak to powinno wyglądać, np:
https://github.com/sp15informatyka/MK_Cplusplus
https://github.com/ksorokosz/HelloWorld

Być może używasz klienta GITa, a nie GitHuba :) Sprawdź ;) Klient GITa jest czymś bardziej skomplikowanym i cieszę się, że spróbowałeś zrobić to zadanie w inny sposób :) Tigersoft spróbuj jeszcze raz być może wystarczy w polu serwer wpisać: github.com i uda Ci się ten kod prawidłowo wrzucić ;) Jeśli nie to spróbuj skorzystać z tutoriala jaki udostępniliśmy, w którym znajdziesz instrukcję krok po kroku jak sobie poradzić z tym zadaniem.

Git to tzw. system kontroli wersji, natomiast GitHub to portal/serwer, który umożliwia korzystanie z dobrodziejstw GITa. Klient GITa wymaga podania serwera, natomiast w kliencie GITHuba po prostu logujemy się na własne konto - serwer :) Jeśli będą zainteresowani to na dzisiejszych zajęciach - na koniec, jeśli zdążymy - pokażę Wam jak korzystać z GITa za pośrednictwem konsoli.

**Comment by EMCsoftware** [comment]
No więc skoro niektórzy wysłali tutaj link, to może lepiej ja też tak postąpię :smile: 
https://github.com/EMCsoftware/ProgramyMistrzowieKodowania/blob/master/HelloWorld.cpp
Na moim tablecie z Windows 10 klient nie może się zainstalować, dlatego też stworzyłem plik przeglądarką :laughing:
