### ISSUE TITLE
Link do pokoju, w którym odbywają się webinary

### ISSUE THREAD

**Issue by kasianw** [MistrzowieKodowania/cPlusPlusMaterials#5]
Trochę naszukałam się tego linku, więc tak sobie pomyślałam, że może ktoś inny też będzie go potrzebować: 
[https://mistrzowiekodowania.clickwebinar.com/cplusplus]

**Comment by tapcia** [comment]
Dzięki ;)

W dniu 9 lutego 2016 18:17 użytkownik kasianw notifications@github.com
napisał:

> Trochę naszukałam się tego linku, więc tak sobie pomyślałam, że może ktoś
> inny też będzie go potrzebować:
> https://mistrzowiekodowania.clickwebinar.com/cplusplus http://url
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/5.

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by sp15informatyka** [comment]
czy możemy uruchomić jakieś irc bo kilka razy wywaliło i nie wiem czy to tylko mój problem, ostatnim razem słuchałem jakiś czas muzyki z brakiem możliwości wejścia a potem wskoczyłem w trakcie bo jak tak to ma wyglądać to ja se chyba pooglądam po jakimś czasie gotowe filmy

**Comment by ksorokosz** [comment]
Link do pokoju wrzuciłem na główną stronę - tam gdzie znajdują się linki do tutoriali ;)
Jeśli chodzi natomiast o problemy techniczne... Niestety mogą one się pojawić zawsze i nie mamy na to zbyt dużego wpływu, trzeba się z nimi po prostu liczyć i próbować "zmniejszać straty" szybko reagując ;)
