### ISSUE TITLE
Zajęcia 4, klasy i obiekty

### ISSUE THREAD

**Issue by ksorokosz** [MistrzowieKodowania/cPlusPlusMaterials#9]
Hej,
przygotowałem już dla Was kod do zajęć 4. Opowiem Wam o klasach w C++ na przykładzie projektu "Grafik". Będzie to oczywiście bardzo niewielki fragment tego projektu, nie zabiorę więc Wam zabawy :) Na kolejnych zajęciach przykłady będą się zmieniać, ale od czegoś trzeba zacząć ;)

Proszę Was również o wypełnienie ankiety:
http://goo.gl/forms/IEwqHCr7yH

Jeśli udałoby się to przez zajęciami byłoby super :) Dzięki temu będę mógł w najbliższym czasie przygotować materiały jakich będziecie potrzebować do zrealizowania tych projektów, do poczytania - z moimi wyjaśnieniami.

**Comment by Tigersoftis** [comment]
po których zajęciach posiądziemy wiedzę, żeby móc takie projekty zrobić ? :)

**Comment by ksorokosz** [comment]
Juz po najblizszych zajeciach bedziecie duzy krok dalej :) sami zobaczycie! zdradze ze juz jutro pobawimy sie pikselami ;)

**Comment by Tigersoftis** [comment]
Wywaliło mnie z webinara, tylko ja mam problem czy wszyscy?

**Comment by ksorokosz** [comment]
mnie też wywaliło i nie bardzo mogę się zalogować :/

**Comment by tapcia** [comment]
Mam to samo, problem Clickwebinara raczej

W dniu 23 lutego 2016 19:48 użytkownik Kamil Sorokosz <
notifications@github.com> napisał:

> mnie też wywaliło i nie bardzo mogę się zalogować :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187837830
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by sp15informatyka** [comment]
No ja siedzę i płaczę w takim ciekawym momencie urwało ...

**Comment by EMCsoftware** [comment]
No ja też mam problemy

**Comment by ksorokosz** [comment]
ma ktoś pomysł na alternatywę z wideo? ;)

**Comment by tapcia** [comment]
Hangout? Skype?

W dniu 23 lutego 2016 19:53 użytkownik Kamil Sorokosz <
notifications@github.com> napisał:

> ma ktoś pomysł na alternatywę z wideo? ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187839680
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by sp15informatyka** [comment]
hangout ?

**Comment by Tigersoftis** [comment]
skypa od wieków nie uzywam a Hangouta nie znam

juz hasła nie pamiętam

**Comment by EMCsoftware** [comment]
Niby na Skype można przez przeglądarkę przez FB, ale jeszcze nie próbowałem. W ogóle nie korzystałem ze Skype.

**Comment by Tigersoftis** [comment]
http://www.trueconf.pl/10-wideokonferencje/44-trueconf-free
http://www.halonet.pl/wideokonferencje/darmowa-wideokonferencja/

**Comment by ksorokosz** [comment]
@Krzysztof13a już zgłasza problem, może wstanie :D poczekajmy chwilę, a ja przejrzę różne możliwości. hangout to taki komunikator google

**Comment by Tigersoftis** [comment]
ooo nieeee nic z googla invigilatora i kolejnego wielkiego brata :)

**Comment by EMCsoftware** [comment]
Wujka

**Comment by sp15informatyka** [comment]
@Tigersoftis Tiger a ty używasz pewno Linuxa :)

**Comment by tapcia** [comment]
Oj tam, Google i tak nie jest tak skuteczne jak Pani spod 4 z mego bloku ;)

W dniu 23 lutego 2016 19:58 użytkownik Seba notifications@github.com
napisał:

> ooo nieeee nic z googla invigilatora i kolejnego wielkiego brata :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187841751
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by Tigersoftis** [comment]
Ja PEGASUSa używam :P

**Comment by EMCsoftware** [comment]
Tak? A ja Atari :smile_cat:

**Comment by sp15informatyka** [comment]
@Tigersoftis no to przepraszam ;)

**Comment by ksorokosz** [comment]
@Tigersoftis 
a nie Atari? :D

**Comment by sp15informatyka** [comment]
Dobra bo Commodora wyciągnę i to 64

**Comment by Tigersoftis** [comment]
ten sam procesor 8 bit :)

**Comment by EMCsoftware** [comment]
A ja Nintendo z lat 80' którego nie posiadam :smile:

**Comment by Tigersoftis** [comment]
a ja mam pegaza i mam tez Atari oraz sege :)
działają i czasem dzieciak gra :)

**Comment by Tigersoftis** [comment]
po kursie napisze OS na PEGAZUSa i wyrzucę Windę :)

tylko zebym zmiescił na jednym ROMie kardridge'a :)

**Comment by EMCsoftware** [comment]
Te 8 bitów to było coś. Niby niewiele, a taki klimat... To nie moje czasy, ale czasem się zagrało w porty na Flash w przeglądarce :wink:

**Comment by sp15informatyka** [comment]
A ja mam teraz raspberry pi i emuluję to wszystko na j maszynie :D

**Comment by Tigersoftis** [comment]
64 kolory a jednoczesnie mógł wyswietlic az 25 :)

**Comment by EMCsoftware** [comment]
A ja mam L293DNE i próbuję zrobić z niego światłoluba :yum: szkoda, że nie mam wprawy w lutowaniu :disappointed:

**Comment by Tigersoftis** [comment]
zagadką dziecinstwa było jak pistolet widzi kaczki na ekranie i wie ze w nie trafiłem lub nie, ale juz wiem :)  na ułamek sekundy ekran zamianiał się w czarny z białą kropką gdzie byla kaczka i fotokomórka w pistolecie to wychwytywała czy nacelowałes na plamkę :) a wzrok nie widział oszustwa :) genialne :)

**Comment by EMCsoftware** [comment]
Ale oszuści wiedzieli, że można strzelać w lampkę

**Comment by sp15informatyka** [comment]
@EMCsoftware na Forbocie zaczął się kurs lutowania polecam

**Comment by EMCsoftware** [comment]
Wiem, ale dopiero się zaczyna, więc...

**Comment by sp15informatyka** [comment]
A sprawdzacie czy działa webinar ? :D

**Comment by Tigersoftis** [comment]
idz na mecz, wkurz dresiarza to Ci przylutuje i zobaczysz jak to się robi w praktyce :)

**Comment by EMCsoftware** [comment]
Nie działa

**Comment by EMCsoftware** [comment]
Dobrze, że chociaż cyna ołowiowa :laughing:

**Comment by Tigersoftis** [comment]
zawsze możesz wziąć ze sobą jeszcze kalafonię :P

ale offtopic sie narobił :)

**Comment by EMCsoftware** [comment]
Mam, ale za wiele mi to nie daje. Mam jeszcze odsysacz, trzecią rękę, multimetr...

**Comment by ksorokosz** [comment]
raspberry pi fajna zabawka :D 
ja co jakiś czas sprawdzam. rozmawiałem z @Krzysztof13a o tym co się stało i ogólnie jest to jakiś globalny problem z clickwebinarem... także @Krzysztof13a wyśle Wam maile z propozycją kiedy robimy webinar :D
jak dla mnie może być jutro lub za tydzień bez robienia 2 tyg.przerwy albo za tydzień z 2 tyg. przerwą po tych zajęciach (wtedy się wszystko przesunie) albo za dwa tygodnie i wtedy też się wszystko przesunie. Jak wolicie?

**Comment by ksorokosz** [comment]
a co do lutowania to polecam dorwać elektronika starej daty i poprosić o naukę :D najlepszy sposób

**Comment by Tigersoftis** [comment]
ja wolał bym za tydzien a resztę przesunąć zeby nadrobic zaległosci :)
siedzę nad tym uczciwie i sie staram ale to zajmuje mi czasu :(

nigdy nie miałem za dobrej głowy do języków obcych :(

**Comment by EMCsoftware** [comment]
A skąd ja takiego wezmę :wink:

**Comment by jakubchojak** [comment]
witam co się stało z tym spotkaniem???
Tylko u mnie nie dział czy to jakiś większy problem?

**Comment by Tigersoftis** [comment]
problem globalny, u nikogo nie działa :(

**Comment by EMCsoftware** [comment]
Wszyscy tu siedzimy i myślimy co robić, bo spotkanie się urwało

**Comment by tapcia** [comment]
Kajoh, większy, wina CLickwebinara.

W dniu 23 lutego 2016 20:12 użytkownik Kajoh123 notifications@github.com
napisał:

> witam co się stało z tym spotkaniem???
> Tylko u mnie nie dział czy to jakiś większy problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187846584
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by jakubchojak** [comment]
ok bo pisało mi że mam odblokować port 1935 ale to (w firewallu) nie pomogło

**Comment by tapcia** [comment]
Powtórka jutro lub za tydzień, dadzą nam znać chłopaki

W dniu 23 lutego 2016 20:14 użytkownik EMCsoftware <notifications@github.com

> napisał:
> 
> Wszyscy tu siedzimy i myślimy co robić, bo spotkanie się urwało
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187847322
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by Krzysztof13a** [comment]
Tak. Wysypał się ClickWebinar, Już stawiają go na nogi. Kamil zaraz się odezwie.

**Comment by sp15informatyka** [comment]
Ale on testuje 3 porty 1935, 443 oraz 80

**Comment by jakubchojak** [comment]
ale powtórka od TEGO momentu (45 minut około) czy całego?

**Comment by Tigersoftis** [comment]
to dzis sie nie odbędzie juz i tak :( albo i  :) 
bedzie wiecej czasu na naukę :)
jesli mozna to i tak prosze o umieszczenie filmiku z tego co było chwilę to bym sie przygotował :)

jutro bedę w trasie bo wracam 300 km do domu :(

**Comment by sp15informatyka** [comment]
no już gra muza

**Comment by Kalibrm** [comment]
Odwołane?

W dniu 23 lutego 2016 20:15 użytkownik Kajoh123 notifications@github.com
napisał:

**Comment by Krzysztof13a** [comment]
Tak. postawili z powrotem. Sebastian - szerokiej drogi.

**Comment by jakubchojak** [comment]
Czy dzisiaj będą zajęcia czy już nie ?

**Comment by Krzysztof13a** [comment]
Dzwonię do Kamila, chwila

**Comment by Tigersoftis** [comment]
mowiłes ze gra muzyka i myslałem ze działa, a tu gra muzyka :)

czemu piszesz ze gra muzyka skoro gra muzyka ? :)

**Comment by jakubchojak** [comment]
Tigersoftis żeś się zapętlił :)

**Comment by EMCsoftware** [comment]
Bo gra muzyka

**Comment by EMCsoftware** [comment]
O, już nie gra

**Comment by tapcia** [comment]
Spoko :)

W dniu 23 lutego 2016 20:19 użytkownik Krzysztof13a <
notifications@github.com> napisał:

> Dzwonię do Kamila, chwila
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187850016
> .

## 

Pozdrawiam
Marta Kostecka
504940644

**Comment by Tigersoftis** [comment]
myslałem ze w potocznym znaczeniu, czyli ze wszystko działa :P

**Comment by Tigersoftis** [comment]
Co mówi informatyk kiedy na urodziny dostaje pendrive? 
- Dziękuję za pamięć.

Jakimi kartami grają informatycy? 
- Kartami graficznymi

tak na rozrywkę w czasie czekania :)

**Comment by heillos** [comment]
Mam taką prośbę, żeby może nie urządzać sobie czata na liście 
dyskusyjnej? Właśnie wróciłem do domu i mam 73 wiadomości do 
przeczytania na mejlu, w tym z 70 waszych czatów :( A potem coś ważnego 
umknie...

W dniu 23.02.2016 o 20:08, Seba pisze:

> idz na mecz, wkurz dresiarza to Ci przylutuje i zobaczysz jak to się 
> robi w praktyce :)
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MistrzowieKodowania/cPlusPlusMaterials/issues/9#issuecomment-187844895.

## 

Przemysław Adam Śmiejek
Zespół Szkół Ogólnokształcących nr 5 w Zabrzu

**Comment by ksorokosz** [comment]
@heillos 
spokojnie ten "czat" spowodowany był problemami z clickwebinarem, na które nikt z nas nie miał wpływu. Część osób w takich sytuacjach czeka w milczeniu, część rezygnuje z webinaru, a część chce utrzymać kontakt z grupą - wg. mnie nie ma nic w tym złego. Github w tym przypadku to nie jest tylko tablica ogłoszeń.... 

Jeśli chodzi o istotne rzeczy - te staram się je wyraźnie zaznaczać. znajdują się w README.md albo rozpoczynają wątki. W kolejnych postach w jednym wątku nigdy nie umieszam, niczego co byłoby bardzo ważne.
